AllCops:
  DisplayCopNames: true
  Exclude:
    - 'config/initializers/devise.rb'
    - 'db/**/*'

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false